### ISSUE TITLE
Fatal exception: TypeError: proc.send is not a function

### ISSUE THREAD

**Issue by damusix** [taskforcesh/bullmq#1120]
Trying to graceful shutdown a server that stops queues and workers before stop and am getting this error:

```
[exiting] Fatal exception: TypeError: proc.send is not a function
    at /project/node_modules/bullmq/src/utils.ts:150:10
    at new Promise (<anonymous>)
    at Object.exports.asyncSend (/project/node_modules/bullmq/src/utils.ts:149:10)
    at Object.exports.childSend (/project/node_modules/bullmq/src/utils.ts:163:21)
    at process.<anonymous> (/project/node_modules/bullmq/src/classes/master.ts:32:9)
    at process.emit (node:events:402:35)
    at process.emit (node:domain:475:12)
    at process.emit.sharedData.processEmitHook.installedValue [as emit] (/project/node_modules/@cspotcode/source-map-support/source-map-support.js:613:40)
    at process._fatalException (node:internal/process/execution:170:25)
```

Here is my graceful shutdown script:

```ts

export interface OurQueue extends Queue {

    scheduler?: QueueScheduler,
    worker?: Worker
}

const gracefulShutdown = async (queue: OurQueue, server: Server) => {

    const bullConnections = [
        queue,
        queue.worker,
        queue.scheduler
    ];

    for (const conn of bullConnections) {

        try { await conn?.close(); }
        catch (err: any) { server.log(['error'], err); }
    }

};
```

**Comment by TemaSM** [comment]
Confirming issue.
Introduced by #1089
