### ISSUE TITLE
Type 'Redis' is not assignable to type 'ConnectionOptions'

### ISSUE THREAD

**Issue by antirek** [taskforcesh/bullmq#1391]
up bullmq deps to 1.89.2, don't compile, error below

in code I create redisConn and pass it to Worker
`````
const redisConn = new Redis(config.WORKER_REDISURL);  // from ioredis
const worker = new Worker(`${config.WORKER_QUEUE}`, async job => {
    return await doWork(job);
  }, {
    connection: redisConn,    
  });
`````

error:
`````
worker/app.ts:133:5 - error TS2322: Type 'Redis' is not assignable to type 'ConnectionOptions'.
  Type 'Redis' is missing the following properties from type 'Redis': stream, isCluster, connector, reconnectTimeout, and 140 more.

133     connection: redisConn,
        ~~~~~~~~~~

  node_modules/bullmq/dist/esm/interfaces/queue-options.d.ts:14:5
    14     connection?: ConnectionOptions;
           ~~~~~~~~~~
    The expected type comes from property 'connection' which is declared here on type 'WorkerOptions'

worker/app.ts:141:5 - error TS2322: Type 'Redis' is not assignable to type 'ConnectionOptions'.

141     connection: redisConn.duplicate(),
        ~~~~~~~~~~

  node_modules/bullmq/dist/esm/interfaces/queue-options.d.ts:14:5
    14     connection?: ConnectionOptions;
           ~~~~~~~~~~
    The expected type comes from property 'connection' which is declared here on type 'QueueSchedulerOptions'


Found 2 errors in the same file, starting at: worker/app.ts:133
`````

**Comment by antirek** [comment]
sorry, up ioredis to actual 5 version

**Comment by ed-asriyan** [comment]
the issue resolved for me after upgrade to 5.2.4 (it did not work on 5.2.1)
