### ISSUE TITLE
[Bug]: 4.15.2 breaking child workers

### ISSUE THREAD

**Issue by andrewpile** [taskforcesh/bullmq#2319]
### Version

v4.15.2

### Platform

NodeJS

### What happened?

Hi-

After upgrading from 4.15.1 to 4.15.2 my child workers are failing with the following: 

```
Error: No function is exported in processor file
    at ChildProcessor.init (/app/node_modules/bullmq/dist/cjs/classes/child-processor.js:33:23)
    at async process.<anonymous> (/app/node_modules/bullmq/dist/cjs/classes/main-base.js:17:21)
```

The child workers are written in ES6 like so:

```
export default async (job) => {
  // Do work
}
```

Then compiled with `esbuild` to `cjs` format. Is `cjs` no longer a supported format?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manast** [comment]
By any chance, could you put a ```console.log(processor)``` after line 24 in child-processor.js? I am curios to see what is it if it is not a function or an object with a default funtion.

**Comment by manast** [comment]
Something else, how does the compiled child worker look like? AFAIK, dynamic imports should support both commonjs and es6 modules. You are using Node16 or newer I suppose?

**Comment by andrewpile** [comment]
> Something else, how does the compiled child worker look like? AFAIK, dynamic imports should support both commonjs and es6 modules. You are using Node16 or newer I suppose?

It's mostly a shim'ed mess but it looks like `esbuild` processed workers generally start with this, with the `export` at the bottom: 

```
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/workers/WorkerExample.js
var WorkerExample_exports = {};
__export(WorkerExample_exports, {
  default: () => WorkerExample_default
});
**module.exports = __toCommonJS(WorkerExample_exports);**
```

I am by no means an expert on this, but it seems that `esbuild`s maintainer agrees with you that this is a mess, [here's the documentation on their export logic](https://esbuild.github.io/content-types/#default-interop).

**Comment by manast** [comment]
@andrewpile can't you separate the processor file from the rest of your build and only build that file with the --format-esm flag?

**Comment by benweissmann** [comment]
We are also hitting this issue. We're using `swc` to compile our child processors.

Our swc config is:

```json
{
  "jsc": {
    "target": "es2022",
    "parser": {
      "syntax": "typescript",
      "tsx": false,
      "decorators": true,
      "dynamicImport": true
    },
    "paths": {
      "~backend/*": ["src/*"],
      "tests/*": ["tests/*"]
    },
    "baseUrl": "."
  },
  "module": {
    "type": "commonjs"
  },
  "sourceMaps": true
}
```

And here's an example compiled worker:

```js
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
Object.defineProperty(exports, "default", {
    enumerable: true,
    get: function() {
        return _default;
    }
});
const _logger = require("@stw/logger");
const _ = require("..");
const _cronErrorHandling = require("../cronErrorHandling");

// withErrorHandling is just a higher-order function that wraps the job function; it returns a function
const processor = (0, _cronErrorHandling.withErrorHandling)(async (_job)=>{
    try {
        await (0, _.enqueueInternalBigQueryExport)();
    } catch (e) {
        _logger.logger.error(e, "Error enqueueing internal bigquery export job");
    }
});
const _default = processor;
```

And the exact error we're seeing is:

```
Error: No function is exported in processor file
  at ChildProcessor.init (/app/node_modules/.pnpm/bullmq@4.15.2/node_modules/bullmq/dist/cjs/classes/child-processor.js:33:23)
  at async process.<anonymous> (/app/node_modules/.pnpm/bullmq@4.15.2/node_modules/bullmq/dist/cjs/classes/main-base.js:17:21)
```

**Comment by manast** [comment]
I added a fix that works with the esbuild generated processor file, https://github.com/taskforcesh/bullmq/pull/2330
@benweissmann let me know if it also helps in your case.

**Comment by manast** [comment]
The fix is available in version 4.15.3
